
#==============================================================================
# START!!! 802_mk_Dataset_425-1.py    PID: 44357    time: 2018-04-25 12:08:34.903260
#==============================================================================

rm: cannot remove '../data/802_tmp*.p': No such file or directory
rm: cannot remove 'SUCCESS_802': No such file or directory
use imp: imp_2018-04-25-09h.csv
['app', 'channel', 'count_app-channel', 'count_app-device-channel', 'count_channel', 'count_ip', 'count_ip-app-os-channel', 'count_ip-channel', 'device', 'hour', 'hour_min', 'ip', 'is_attributed', 'nunique_app-channel_channel', 'nunique_app-device-os-channel_app-channel', 'nunique_app-device-os-channel_app-device-os', 'nunique_app-device-os-channel_app-os', 'nunique_app-device-os_app-device', 'nunique_app-os-channel_app-channel', 'nunique_app-os-channel_app-os', 'nunique_device-channel_channel', 'nunique_device-os-channel_channel', 'nunique_ip-app-channel_ip', 'nunique_ip-app-channel_ip-app', 'nunique_ip-app-device-channel_app-device-channel', 'nunique_ip-app-device-channel_ip-device', 'nunique_ip-app-device-os-channel_app-device', 'nunique_ip-app-device-os-channel_app-device-channel', 'nunique_ip-app-device-os-channel_ip-device-channel', 'nunique_ip-app-device-os-channel_ip-os', 'nunique_ip-app-device-os_app-device', 'nunique_ip-app-device-os_ip-app', 'nunique_ip-app-device-os_ip-os', 'nunique_ip-app-device_ip-device', 'nunique_ip-app-os-channel_app-channel', 'nunique_ip-app-os_app', 'nunique_ip-app_ip', 'nunique_ip-channel_ip', 'nunique_ip-device-os_ip-device', 'nunique_ip-device_ip', 'nunique_ip-os_ip', 'os', 'sameClickTimeCount_app', 'sameClickTimeCount_app-channel', 'sameClickTimeCount_app-device', 'timedelta_rev_ip-app', 'timedelta_rev_ip-app-device', 'timedelta_rev_ip-app-device-os', 'timedelta_rev_ip-app-device-os-channel', 'timedelta_rev_ip-app-os-channel', 'timedelta_rev_ip-channel', 'timedelta_rev_ip-device-os', 'timestamp', 'totalcount_app', 'totalcount_app-channel', 'totalcount_app-device', 'totalcount_device-os', 'totalcount_ip', 'totalcount_ip-app', 'totalcount_ip-device', 'totalcount_ip-device-os']
loading ../data/101_train/ ...
loading ../data/103-3_train/ ...
loading ../data/103-2_train/ ...
loading ../data/104-2_train/ ...
loading ../data/004_train/ ...
loading ../data/002_train/ ...
loading ../data/104-1_train/ ...
loading ../data/001_train/ ...
loading ../data/103-1_train/ ...
loading ../data/102_train/ ...
loading ../data/104-3_train/ ...
loading ../data/105-1_train/ ...
loading ../data/105-2_train/ ...
loading ../data/106-1_train/ ...
loading ../data/106-2_train/ ...
loading ../data/106-3_train/ ...
loading ../data/107-1_train/ ...
loading ../data/107-2_train/ ...
loading ../data/108-1_train/ ...
loading ../data/108-2_train/ ...
loading ../data/108-3_train/ ...
loading ../data/112_train/ ...
loading ../data/train/ ...
concat train
X.isnull().sum().sum(): 0
rm: cannot remove '../data/dtrain.mt': No such file or directory
[LightGBM] [Info] Saving data to binary file ../data/dtrain.mt
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [00:00<00:34,  2.90it/s]  2%|▏         | 2/100 [00:00<00:35,  2.72it/s]  3%|▎         | 3/100 [00:01<00:33,  2.91it/s]  4%|▍         | 4/100 [00:01<00:32,  2.96it/s]  5%|▌         | 5/100 [00:01<00:29,  3.19it/s]  6%|▌         | 6/100 [00:01<00:28,  3.32it/s]  7%|▋         | 7/100 [00:02<00:27,  3.33it/s]  8%|▊         | 8/100 [00:02<00:27,  3.38it/s]  9%|▉         | 9/100 [00:02<00:26,  3.38it/s] 10%|█         | 10/100 [00:02<00:25,  3.54it/s] 11%|█         | 11/100 [00:03<00:25,  3.47it/s] 12%|█▏        | 12/100 [00:03<00:25,  3.41it/s] 13%|█▎        | 13/100 [00:03<00:25,  3.42it/s] 14%|█▍        | 14/100 [00:04<00:24,  3.48it/s] 15%|█▌        | 15/100 [00:04<00:23,  3.55it/s] 16%|█▌        | 16/100 [00:04<00:23,  3.51it/s] 17%|█▋        | 17/100 [00:04<00:23,  3.57it/s] 18%|█▊        | 18/100 [00:04<00:22,  3.62it/s] 19%|█▉        | 19/100 [00:05<00:21,  3.70it/s] 20%|██        | 20/100 [00:05<00:21,  3.64it/s] 21%|██        | 21/100 [00:05<00:21,  3.63it/s] 22%|██▏       | 22/100 [00:06<00:21,  3.65it/s] 23%|██▎       | 23/100 [00:06<00:20,  3.68it/s] 24%|██▍       | 24/100 [00:06<00:20,  3.69it/s] 25%|██▌       | 25/100 [00:06<00:20,  3.70it/s] 26%|██▌       | 26/100 [00:06<00:19,  3.75it/s] 27%|██▋       | 27/100 [00:07<00:19,  3.79it/s] 28%|██▊       | 28/100 [00:07<00:18,  3.82it/s] 29%|██▉       | 29/100 [00:07<00:18,  3.84it/s] 30%|███       | 30/100 [00:07<00:18,  3.83it/s] 31%|███       | 31/100 [00:07<00:17,  3.88it/s] 32%|███▏      | 32/100 [00:08<00:17,  3.91it/s] 33%|███▎      | 33/100 [00:08<00:16,  3.95it/s] 34%|███▍      | 34/100 [00:08<00:16,  3.98it/s] 35%|███▌      | 35/100 [00:08<00:16,  3.95it/s] 36%|███▌      | 36/100 [00:09<00:16,  3.95it/s] 37%|███▋      | 37/100 [00:09<00:16,  3.93it/s] 38%|███▊      | 38/100 [00:09<00:15,  3.97it/s] 39%|███▉      | 39/100 [00:09<00:15,  3.98it/s] 40%|████      | 40/100 [00:09<00:14,  4.00it/s] 41%|████      | 41/100 [00:10<00:14,  4.03it/s] 42%|████▏     | 42/100 [00:10<00:14,  4.04it/s] 43%|████▎     | 43/100 [00:10<00:14,  4.05it/s] 44%|████▍     | 44/100 [00:10<00:13,  4.01it/s] 45%|████▌     | 45/100 [00:11<00:13,  3.97it/s] 46%|████▌     | 46/100 [00:11<00:13,  3.96it/s] 47%|████▋     | 47/100 [00:11<00:13,  3.98it/s] 48%|████▊     | 48/100 [00:12<00:13,  3.99it/s] 49%|████▉     | 49/100 [00:12<00:12,  4.00it/s] 50%|█████     | 50/100 [00:12<00:12,  4.00it/s] 51%|█████     | 51/100 [00:12<00:12,  3.98it/s] 52%|█████▏    | 52/100 [00:13<00:12,  3.98it/s] 53%|█████▎    | 53/100 [00:13<00:11,  3.94it/s] 54%|█████▍    | 54/100 [00:13<00:11,  3.94it/s] 55%|█████▌    | 55/100 [00:13<00:11,  3.94it/s] 56%|█████▌    | 56/100 [00:14<00:11,  3.94it/s] 57%|█████▋    | 57/100 [00:14<00:10,  3.95it/s] 58%|█████▊    | 58/100 [00:14<00:10,  3.97it/s] 59%|█████▉    | 59/100 [00:14<00:10,  4.01it/s] 60%|██████    | 60/100 [00:15<00:10,  3.99it/s] 61%|██████    | 61/100 [00:15<00:09,  4.01it/s] 62%|██████▏   | 62/100 [00:15<00:09,  4.01it/s] 63%|██████▎   | 63/100 [00:15<00:09,  4.03it/s] 64%|██████▍   | 64/100 [00:15<00:08,  4.02it/s] 65%|██████▌   | 65/100 [00:16<00:08,  4.04it/s] 66%|██████▌   | 66/100 [00:16<00:08,  4.02it/s] 67%|██████▋   | 67/100 [00:16<00:08,  4.03it/s] 68%|██████▊   | 68/100 [00:16<00:07,  4.04it/s] 69%|██████▉   | 69/100 [00:17<00:07,  4.05it/s] 70%|███████   | 70/100 [00:17<00:07,  4.06it/s] 71%|███████   | 71/100 [00:17<00:07,  4.04it/s] 72%|███████▏  | 72/100 [00:17<00:06,  4.05it/s] 73%|███████▎  | 73/100 [00:18<00:06,  4.05it/s] 74%|███████▍  | 74/100 [00:18<00:06,  4.07it/s] 75%|███████▌  | 75/100 [00:18<00:06,  4.06it/s] 76%|███████▌  | 76/100 [00:18<00:05,  4.07it/s] 77%|███████▋  | 77/100 [00:18<00:05,  4.09it/s] 78%|███████▊  | 78/100 [00:19<00:05,  4.09it/s] 79%|███████▉  | 79/100 [00:19<00:05,  4.10it/s] 80%|████████  | 80/100 [00:19<00:04,  4.09it/s] 81%|████████  | 81/100 [00:19<00:04,  4.10it/s] 82%|████████▏ | 82/100 [00:20<00:04,  4.09it/s] 83%|████████▎ | 83/100 [00:20<00:04,  4.08it/s] 84%|████████▍ | 84/100 [00:20<00:03,  4.09it/s] 85%|████████▌ | 85/100 [00:20<00:03,  4.10it/s] 86%|████████▌ | 86/100 [00:20<00:03,  4.10it/s] 87%|████████▋ | 87/100 [00:21<00:03,  3.98it/s] 88%|████████▊ | 88/100 [00:22<00:03,  3.88it/s] 89%|████████▉ | 89/100 [00:24<00:03,  3.60it/s] 90%|█████████ | 90/100 [00:26<00:02,  3.41it/s] 91%|█████████ | 91/100 [00:27<00:02,  3.27it/s] 92%|█████████▏| 92/100 [00:29<00:02,  3.13it/s] 93%|█████████▎| 93/100 [00:31<00:02,  2.98it/s] 94%|█████████▍| 94/100 [00:32<00:02,  2.86it/s] 95%|█████████▌| 95/100 [00:34<00:01,  2.74it/s] 96%|█████████▌| 96/100 [00:35<00:01,  2.71it/s] 97%|█████████▋| 97/100 [00:37<00:01,  2.61it/s] 98%|█████████▊| 98/100 [00:38<00:00,  2.55it/s] 99%|█████████▉| 99/100 [00:40<00:00,  2.47it/s]100%|██████████| 100/100 [00:41<00:00,  2.43it/s]
loading ../data/102_test/ ...
loading ../data/103-3_test/ ...
loading ../data/104-3_test/ ...
loading ../data/001_test/ ...
loading ../data/105-1_test/ ...
loading ../data/103-1_test/ ...
loading ../data/106-1_test/ ...
loading ../data/103-2_test/ ...
loading ../data/101_test/ ...
loading ../data/104-2_test/ ...
loading ../data/104-1_test/ ...
loading ../data/105-2_test/ ...
loading ../data/004_test/ ...
loading ../data/002_test/ ...
loading ../data/107-1_test/ ...
loading ../data/106-3_test/ ...
loading ../data/107-2_test/ ...
loading ../data/108-2_test/ ...
loading ../data/112_test/ ...
loading ../data/test_old/ ...
loading ../data/108-1_test/ ...
loading ../data/108-3_test/ ...
loading ../data/106-2_test/ ...
  0%|          | 0/100 [00:00<?, ?it/s]  4%|▍         | 4/100 [00:00<00:03, 31.71it/s]  8%|▊         | 8/100 [00:00<00:02, 32.49it/s] 12%|█▏        | 12/100 [00:00<00:02, 32.80it/s] 16%|█▌        | 16/100 [00:00<00:02, 32.96it/s] 20%|██        | 20/100 [00:00<00:02, 33.09it/s] 24%|██▍       | 24/100 [00:00<00:02, 33.12it/s] 28%|██▊       | 28/100 [00:00<00:02, 33.15it/s] 32%|███▏      | 32/100 [00:00<00:02, 33.18it/s] 36%|███▌      | 36/100 [00:01<00:01, 33.19it/s] 40%|████      | 40/100 [00:01<00:01, 33.24it/s] 44%|████▍     | 44/100 [00:01<00:01, 33.28it/s] 48%|████▊     | 48/100 [00:01<00:01, 33.42it/s] 52%|█████▏    | 52/100 [00:01<00:01, 32.21it/s] 57%|█████▋    | 57/100 [00:01<00:01, 33.03it/s] 62%|██████▏   | 62/100 [00:01<00:01, 33.71it/s] 67%|██████▋   | 67/100 [00:01<00:00, 34.34it/s] 72%|███████▏  | 72/100 [00:02<00:00, 34.90it/s] 77%|███████▋  | 77/100 [00:02<00:00, 35.41it/s] 82%|████████▏ | 82/100 [00:02<00:00, 35.91it/s] 87%|████████▋ | 87/100 [00:02<00:00, 36.37it/s] 92%|█████████▏| 92/100 [00:02<00:00, 36.75it/s] 97%|█████████▋| 97/100 [00:02<00:00, 37.08it/s]100%|██████████| 100/100 [00:02<00:00, 37.28it/s]
../data/test_old/ (18790469, 7)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 83, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 88, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 94, in read_pickle
    return try_read(path)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 92, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 83, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 88, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "802_mk_Dataset_425-1.py", line 86, in multi_test
    df = pd.read_pickle(load_folder + '/0.p')
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 97, in read_pickle
    return try_read(path, encoding='latin1')
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 92, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 66, in read_wrapper
    is_text=False)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/site-packages/pandas/io/common.py", line 388, in _get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "802_mk_Dataset_425-1.py", line 146, in <module>
    pool.map(multi_test, args)
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kazuki_onodera/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '../data/104-3_test//0.p'
